prefix = "."
stop-words = "stopwords.txt"

dataset = "data"
corpus = "file.toml"
index = "idx"
uninvert = true

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[[analyzers]]
method = "ngram-word"
ngram = 2
filter = "default-chain"