prefix = "."
stop-words = "stopwords.txt"

dataset = "uiuc-textinfo"
corpus = "file.toml"
index = "txtinfo-idx"
uninvert = true

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
#file = "uiuc-text-info-filter.txt"
#type = "reject"

[[analyzers]]
method = "ngram-word"
ngram = 2
filter = "default-chain"