stop-words = "stopwords.txt"
prefix = "."
dataset = "uiuc-textinfo"
index = "txtinfo-idx"
corpus = "file.toml"
uninvert = true
[[analyzers]]
	filter = "default-unigram-chain"
	method = "ngram-word"
	ngram = 1
[[analyzers]]
	filter = "default-chain"
	method = "ngram-word"
	ngram = 2
