type = "file-corpus"
store-full-text = true
list = "uiuc-text-mining-analytics"
encoding = "utf-8"
#num-docs = 93
metadata = [{name = "title", type = "string"},
			{name = "path", type = "string"},
			{name = "url", type = "string"},
			{name = "playlist_id", type = "string"},
			{name = "description", type = "string"}]  